indira_simoni_homepage:
    pattern:  /
    defaults: { _controller: IndiraSimoniBundle:Default:index }

indira_simoni_registro:
    pattern:  /registro
    defaults: { _controller: IndiraSimoniBundle:Default:registro }

indira_simoni_monitoreo:
    pattern:  /monitoreo
    defaults: { _controller: IndiraSimoniBundle:Default:monitoreo }

indira_simoni_search:
    pattern:  /search
    defaults: { _controller: IndiraSimoniBundle:Default:search }

IndiraSimoniBundle_document:
    resource: "@IndiraSimoniBundle/Resources/config/routing/document.yml"
    prefix:   /document

IndiraSimoniBundle_avistamientoimportado:
    resource: "@IndiraSimoniBundle/Resources/config/routing/avistamientoimportado.yml"
    prefix:   /avistamientoimportado

IndiraSimoniBundle_denuncia:
    resource: "@IndiraSimoniBundle/Resources/config/routing/denuncia.yml"
    prefix:   /denuncia

IndiraSimoniBundle_imagen:
    resource: "@IndiraSimoniBundle/Resources/config/routing/imagen.yml"
    prefix:   /imagen

IndiraSimoniBundle_imagendenuncia:
    resource: "@IndiraSimoniBundle/Resources/config/routing/imagendenuncia.yml"
    prefix:   /imagendenuncia

IndiraSimoniBundle_ejemplar:
    resource: "@IndiraSimoniBundle/Resources/config/routing/ejemplar.yml"
    prefix:   /ejemplar
