<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130617011515 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE fos_user ADD nombre VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD apellidos VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD identidad VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD fechaDeNacimiento TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD telefono VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD direccion VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD departamento VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD pais VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD nivelEducativo VARCHAR(255) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE fos_user DROP nombre");
        $this->addSql("ALTER TABLE fos_user DROP apellidos");
        $this->addSql("ALTER TABLE fos_user DROP identidad");
        $this->addSql("ALTER TABLE fos_user DROP fechaDeNacimiento");
        $this->addSql("ALTER TABLE fos_user DROP telefono");
        $this->addSql("ALTER TABLE fos_user DROP direccion");
        $this->addSql("ALTER TABLE fos_user DROP departamento");
        $this->addSql("ALTER TABLE fos_user DROP pais");
        $this->addSql("ALTER TABLE fos_user DROP nivelEducativo");
    }
}
