<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130720181857 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE atributoclave ALTER descripcion DROP NOT NULL");
        $this->addSql("ALTER TABLE beneficiario ADD descripcion TEXT DEFAULT NULL");
        $this->addSql("ALTER TABLE indicador ADD rango1 VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE indicador ADD rango2 VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE indicador ADD rango3 VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE indicador ADD rango4 VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE indicador ALTER descripcion DROP NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE Beneficiario DROP descripcion");
        $this->addSql("ALTER TABLE AtributoClave ALTER descripcion SET NOT NULL");
        $this->addSql("ALTER TABLE Indicador DROP rango1");
        $this->addSql("ALTER TABLE Indicador DROP rango2");
        $this->addSql("ALTER TABLE Indicador DROP rango3");
        $this->addSql("ALTER TABLE Indicador DROP rango4");
        $this->addSql("ALTER TABLE Indicador ALTER descripcion SET NOT NULL");
    }
}
