<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130706114640 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE denuncia ADD usuario_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE denuncia ADD CONSTRAINT FK_D5505C0DB38439E FOREIGN KEY (usuario_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE INDEX IDX_D5505C0DB38439E ON denuncia (usuario_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE Denuncia DROP usuario_id");
        $this->addSql("ALTER TABLE Denuncia DROP CONSTRAINT FK_D5505C0DB38439E");
        $this->addSql("DROP INDEX IDX_D5505C0DB38439E");
    }
}
