<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130703150012 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE SEQUENCE Imagen_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE Imagen (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, path VARCHAR(255) DEFAULT NULL, avistamientoImportado_id INT DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_84B5D78543630888 ON Imagen (avistamientoImportado_id)");
        $this->addSql("ALTER TABLE Imagen ADD CONSTRAINT FK_84B5D78543630888 FOREIGN KEY (avistamientoImportado_id) REFERENCES AvistamientoImportado (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("DROP SEQUENCE Imagen_id_seq CASCADE");
        $this->addSql("DROP TABLE Imagen");
    }
}
