<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130616235314 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE TABLE Avistamiento (id INT NOT NULL, especie_id INT DEFAULT NULL, tipo_avistamiento_id INT DEFAULT NULL, municipio_id INT DEFAULT NULL, zona_id INT DEFAULT NULL, user_id INT DEFAULT NULL, edad_id INT DEFAULT NULL, sexo_id INT DEFAULT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cantidad INT DEFAULT NULL, latitud NUMERIC(12, 9) DEFAULT NULL, longitud NUMERIC(12, 9) DEFAULT NULL, comentario TEXT DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_DF248549E70ED95B ON Avistamiento (especie_id)");
        $this->addSql("CREATE INDEX IDX_DF2485493D62B5C6 ON Avistamiento (tipo_avistamiento_id)");
        $this->addSql("CREATE INDEX IDX_DF24854958BC1BE0 ON Avistamiento (municipio_id)");
        $this->addSql("CREATE INDEX IDX_DF248549104EA8FC ON Avistamiento (zona_id)");
        $this->addSql("CREATE INDEX IDX_DF248549A76ED395 ON Avistamiento (user_id)");
        $this->addSql("CREATE INDEX IDX_DF2485495E91D3FB ON Avistamiento (edad_id)");
        $this->addSql("CREATE INDEX IDX_DF2485492B32DB58 ON Avistamiento (sexo_id)");
        $this->addSql("CREATE TABLE AvistamientoImportado (id INT NOT NULL, clase_id INT DEFAULT NULL, tipo_avistamiento_id INT DEFAULT NULL, municipio_id INT DEFAULT NULL, zona_id INT DEFAULT NULL, user_id INT DEFAULT NULL, edad_id INT DEFAULT NULL, reino_id INT DEFAULT NULL, sexo_id INT DEFAULT NULL, nombre_comun VARCHAR(255) DEFAULT NULL, nombre_cientifico VARCHAR(255) DEFAULT NULL, genero VARCHAR(255) DEFAULT NULL, localidad VARCHAR(255) DEFAULT NULL, especie VARCHAR(255) DEFAULT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cantidad INT DEFAULT NULL, latitud NUMERIC(12, 9) DEFAULT NULL, longitud NUMERIC(12, 9) DEFAULT NULL, comentario TEXT DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_89AA03B29F720353 ON AvistamientoImportado (clase_id)");
        $this->addSql("CREATE INDEX IDX_89AA03B23D62B5C6 ON AvistamientoImportado (tipo_avistamiento_id)");
        $this->addSql("CREATE INDEX IDX_89AA03B258BC1BE0 ON AvistamientoImportado (municipio_id)");
        $this->addSql("CREATE INDEX IDX_89AA03B2104EA8FC ON AvistamientoImportado (zona_id)");
        $this->addSql("CREATE INDEX IDX_89AA03B2A76ED395 ON AvistamientoImportado (user_id)");
        $this->addSql("CREATE INDEX IDX_89AA03B25E91D3FB ON AvistamientoImportado (edad_id)");
        $this->addSql("CREATE INDEX IDX_89AA03B2A165460F ON AvistamientoImportado (reino_id)");
        $this->addSql("CREATE INDEX IDX_89AA03B22B32DB58 ON AvistamientoImportado (sexo_id)");
        $this->addSql("CREATE TABLE Clase (id INT NOT NULL, reino_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_D85E83CAA165460F ON Clase (reino_id)");
        $this->addSql("CREATE TABLE Document (id INT NOT NULL, user_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, path VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_211FE820A76ED395 ON Document (user_id)");
        $this->addSql("CREATE TABLE Edad (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, color VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE Especie (id INT NOT NULL, reino_id INT DEFAULT NULL, nombre_comun VARCHAR(255) DEFAULT NULL, genero VARCHAR(255) DEFAULT NULL, especie VARCHAR(255) DEFAULT NULL, nombre_cientifico VARCHAR(255) DEFAULT NULL, descripcion TEXT DEFAULT NULL, nombre_pech VARCHAR(255) DEFAULT NULL, nombre_tawaka VARCHAR(255) DEFAULT NULL, nombre_garifuna VARCHAR(255) DEFAULT NULL, nombre_misquito VARCHAR(255) DEFAULT NULL, UICN VARCHAR(255) DEFAULT NULL, CITES VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_30B52D71A165460F ON Especie (reino_id)");
        $this->addSql("CREATE TABLE Municipio (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, color VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE Reino (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, color VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE Sexo (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, color VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE TipoAvistamiento (id INT NOT NULL, reino_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, color VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_A3826232A165460F ON TipoAvistamiento (reino_id)");
        $this->addSql("CREATE TABLE fos_user (id INT NOT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, enabled BOOLEAN NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, locked BOOLEAN NOT NULL, expired BOOLEAN NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, roles TEXT NOT NULL, credentials_expired BOOLEAN NOT NULL, credentials_expire_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_957A647992FC23A8 ON fos_user (username_canonical)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_957A6479A0D96FBF ON fos_user (email_canonical)");
        $this->addSql("COMMENT ON COLUMN fos_user.roles IS '(DC2Type:array)'");
        $this->addSql("CREATE TABLE Zona (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, color VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("ALTER TABLE Avistamiento ADD CONSTRAINT FK_DF248549E70ED95B FOREIGN KEY (especie_id) REFERENCES Especie (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Avistamiento ADD CONSTRAINT FK_DF2485493D62B5C6 FOREIGN KEY (tipo_avistamiento_id) REFERENCES TipoAvistamiento (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Avistamiento ADD CONSTRAINT FK_DF24854958BC1BE0 FOREIGN KEY (municipio_id) REFERENCES Municipio (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Avistamiento ADD CONSTRAINT FK_DF248549104EA8FC FOREIGN KEY (zona_id) REFERENCES Zona (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Avistamiento ADD CONSTRAINT FK_DF248549A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Avistamiento ADD CONSTRAINT FK_DF2485495E91D3FB FOREIGN KEY (edad_id) REFERENCES Edad (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Avistamiento ADD CONSTRAINT FK_DF2485492B32DB58 FOREIGN KEY (sexo_id) REFERENCES Sexo (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE AvistamientoImportado ADD CONSTRAINT FK_89AA03B29F720353 FOREIGN KEY (clase_id) REFERENCES Clase (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE AvistamientoImportado ADD CONSTRAINT FK_89AA03B23D62B5C6 FOREIGN KEY (tipo_avistamiento_id) REFERENCES TipoAvistamiento (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE AvistamientoImportado ADD CONSTRAINT FK_89AA03B258BC1BE0 FOREIGN KEY (municipio_id) REFERENCES Municipio (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE AvistamientoImportado ADD CONSTRAINT FK_89AA03B2104EA8FC FOREIGN KEY (zona_id) REFERENCES Zona (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE AvistamientoImportado ADD CONSTRAINT FK_89AA03B2A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE AvistamientoImportado ADD CONSTRAINT FK_89AA03B25E91D3FB FOREIGN KEY (edad_id) REFERENCES Edad (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE AvistamientoImportado ADD CONSTRAINT FK_89AA03B2A165460F FOREIGN KEY (reino_id) REFERENCES Reino (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE AvistamientoImportado ADD CONSTRAINT FK_89AA03B22B32DB58 FOREIGN KEY (sexo_id) REFERENCES Sexo (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Clase ADD CONSTRAINT FK_D85E83CAA165460F FOREIGN KEY (reino_id) REFERENCES Reino (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Document ADD CONSTRAINT FK_211FE820A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Especie ADD CONSTRAINT FK_30B52D71A165460F FOREIGN KEY (reino_id) REFERENCES Reino (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE TipoAvistamiento ADD CONSTRAINT FK_A3826232A165460F FOREIGN KEY (reino_id) REFERENCES Reino (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE AvistamientoImportado DROP CONSTRAINT FK_89AA03B29F720353");
        $this->addSql("ALTER TABLE Avistamiento DROP CONSTRAINT FK_DF2485495E91D3FB");
        $this->addSql("ALTER TABLE AvistamientoImportado DROP CONSTRAINT FK_89AA03B25E91D3FB");
        $this->addSql("ALTER TABLE Avistamiento DROP CONSTRAINT FK_DF248549E70ED95B");
        $this->addSql("ALTER TABLE Avistamiento DROP CONSTRAINT FK_DF24854958BC1BE0");
        $this->addSql("ALTER TABLE AvistamientoImportado DROP CONSTRAINT FK_89AA03B258BC1BE0");
        $this->addSql("ALTER TABLE AvistamientoImportado DROP CONSTRAINT FK_89AA03B2A165460F");
        $this->addSql("ALTER TABLE Clase DROP CONSTRAINT FK_D85E83CAA165460F");
        $this->addSql("ALTER TABLE Especie DROP CONSTRAINT FK_30B52D71A165460F");
        $this->addSql("ALTER TABLE TipoAvistamiento DROP CONSTRAINT FK_A3826232A165460F");
        $this->addSql("ALTER TABLE Avistamiento DROP CONSTRAINT FK_DF2485492B32DB58");
        $this->addSql("ALTER TABLE AvistamientoImportado DROP CONSTRAINT FK_89AA03B22B32DB58");
        $this->addSql("ALTER TABLE Avistamiento DROP CONSTRAINT FK_DF2485493D62B5C6");
        $this->addSql("ALTER TABLE AvistamientoImportado DROP CONSTRAINT FK_89AA03B23D62B5C6");
        $this->addSql("ALTER TABLE Avistamiento DROP CONSTRAINT FK_DF248549A76ED395");
        $this->addSql("ALTER TABLE AvistamientoImportado DROP CONSTRAINT FK_89AA03B2A76ED395");
        $this->addSql("ALTER TABLE Document DROP CONSTRAINT FK_211FE820A76ED395");
        $this->addSql("ALTER TABLE Avistamiento DROP CONSTRAINT FK_DF248549104EA8FC");
        $this->addSql("ALTER TABLE AvistamientoImportado DROP CONSTRAINT FK_89AA03B2104EA8FC");
        $this->addSql("DROP TABLE Avistamiento");
        $this->addSql("DROP TABLE AvistamientoImportado");
        $this->addSql("DROP TABLE Clase");
        $this->addSql("DROP TABLE Document");
        $this->addSql("DROP TABLE Edad");
        $this->addSql("DROP TABLE Especie");
        $this->addSql("DROP TABLE Municipio");
        $this->addSql("DROP TABLE Reino");
        $this->addSql("DROP TABLE Sexo");
        $this->addSql("DROP TABLE TipoAvistamiento");
        $this->addSql("DROP TABLE fos_user");
        $this->addSql("DROP TABLE Zona");
    }
}
