<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130708203733 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE SEQUENCE AtributoClave_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE Beneficiario_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE Dimension_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE Indicador_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE SubDimension_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE TipoIndicador_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE AtributoClave (id INT NOT NULL, beneficiario_id INT DEFAULT NULL, descripcion VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_D7348F5C4B64ABC7 ON AtributoClave (beneficiario_id)");
        $this->addSql("CREATE TABLE Beneficiario (id INT NOT NULL, subdimension_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, imagen VARCHAR(255) NOT NULL, color VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_F0E16DEF9C30EFCD ON Beneficiario (subdimension_id)");
        $this->addSql("CREATE TABLE Dimension (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, imagen VARCHAR(255) NOT NULL, color VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE Indicador (id INT NOT NULL, atributoclave_id INT DEFAULT NULL, tipo_id INT DEFAULT NULL, descripcion VARCHAR(255) NOT NULL, nivel INT NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_4FE3BC6070017B29 ON Indicador (atributoclave_id)");
        $this->addSql("CREATE INDEX IDX_4FE3BC60A9276E6C ON Indicador (tipo_id)");
        $this->addSql("CREATE TABLE SubDimension (id INT NOT NULL, dimension_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, imagen VARCHAR(255) NOT NULL, color VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_C43433FE277428AD ON SubDimension (dimension_id)");
        $this->addSql("CREATE TABLE TipoIndicador (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("ALTER TABLE AtributoClave ADD CONSTRAINT FK_D7348F5C4B64ABC7 FOREIGN KEY (beneficiario_id) REFERENCES Beneficiario (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Beneficiario ADD CONSTRAINT FK_F0E16DEF9C30EFCD FOREIGN KEY (subdimension_id) REFERENCES SubDimension (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Indicador ADD CONSTRAINT FK_4FE3BC6070017B29 FOREIGN KEY (atributoclave_id) REFERENCES AtributoClave (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Indicador ADD CONSTRAINT FK_4FE3BC60A9276E6C FOREIGN KEY (tipo_id) REFERENCES TipoIndicador (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE SubDimension ADD CONSTRAINT FK_C43433FE277428AD FOREIGN KEY (dimension_id) REFERENCES Dimension (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE Indicador DROP CONSTRAINT FK_4FE3BC6070017B29");
        $this->addSql("ALTER TABLE AtributoClave DROP CONSTRAINT FK_D7348F5C4B64ABC7");
        $this->addSql("ALTER TABLE SubDimension DROP CONSTRAINT FK_C43433FE277428AD");
        $this->addSql("ALTER TABLE Beneficiario DROP CONSTRAINT FK_F0E16DEF9C30EFCD");
        $this->addSql("ALTER TABLE Indicador DROP CONSTRAINT FK_4FE3BC60A9276E6C");
        $this->addSql("DROP SEQUENCE AtributoClave_id_seq CASCADE");
        $this->addSql("DROP SEQUENCE Beneficiario_id_seq CASCADE");
        $this->addSql("DROP SEQUENCE Dimension_id_seq CASCADE");
        $this->addSql("DROP SEQUENCE Indicador_id_seq CASCADE");
        $this->addSql("DROP SEQUENCE SubDimension_id_seq CASCADE");
        $this->addSql("DROP SEQUENCE TipoIndicador_id_seq CASCADE");
        $this->addSql("DROP TABLE AtributoClave");
        $this->addSql("DROP TABLE Beneficiario");
        $this->addSql("DROP TABLE Dimension");
        $this->addSql("DROP TABLE Indicador");
        $this->addSql("DROP TABLE SubDimension");
        $this->addSql("DROP TABLE TipoIndicador");
    }
}
