<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130803192311 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE imagendenuncia ADD image_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE imagendenuncia DROP path");
        $this->addSql("ALTER TABLE imagendenuncia ADD CONSTRAINT FK_768B27213DA5256D FOREIGN KEY (image_id) REFERENCES media__media (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE INDEX IDX_768B27213DA5256D ON imagendenuncia (image_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE SEQUENCE acl_entries_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE acl_security_identities_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE acl_classes_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE acl_object_identities_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("ALTER TABLE ImagenDenuncia ADD path VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE ImagenDenuncia DROP image_id");
        $this->addSql("ALTER TABLE ImagenDenuncia DROP CONSTRAINT FK_768B27213DA5256D");
        $this->addSql("DROP INDEX IDX_768B27213DA5256D");
        $this->addSql("ALTER TABLE fos_user ALTER created_at DROP NOT NULL");
        $this->addSql("ALTER TABLE fos_user ALTER updated_at DROP NOT NULL");
    }
}
