<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130706142656 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE SEQUENCE Coordenada_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE Ejemplar_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE Coordenada (id INT NOT NULL, denuncia_id INT DEFAULT NULL, latitud NUMERIC(9, 2) DEFAULT NULL, longitud NUMERIC(9, 2) DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_C9E828E17048D94 ON Coordenada (denuncia_id)");
        $this->addSql("CREATE TABLE Ejemplar (id INT NOT NULL, sexo_id INT DEFAULT NULL, edad_id INT DEFAULT NULL, avistamiento_id INT DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_FA1DF5702B32DB58 ON Ejemplar (sexo_id)");
        $this->addSql("CREATE INDEX IDX_FA1DF5705E91D3FB ON Ejemplar (edad_id)");
        $this->addSql("CREATE INDEX IDX_FA1DF570EB38C5E1 ON Ejemplar (avistamiento_id)");
        $this->addSql("ALTER TABLE Coordenada ADD CONSTRAINT FK_C9E828E17048D94 FOREIGN KEY (denuncia_id) REFERENCES Denuncia (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Ejemplar ADD CONSTRAINT FK_FA1DF5702B32DB58 FOREIGN KEY (sexo_id) REFERENCES Sexo (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Ejemplar ADD CONSTRAINT FK_FA1DF5705E91D3FB FOREIGN KEY (edad_id) REFERENCES Edad (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Ejemplar ADD CONSTRAINT FK_FA1DF570EB38C5E1 FOREIGN KEY (avistamiento_id) REFERENCES AvistamientoImportado (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE avistamientoimportado DROP CONSTRAINT fk_89aa03b25e91d3fb");
        $this->addSql("ALTER TABLE avistamientoimportado DROP CONSTRAINT fk_89aa03b22b32db58");
        $this->addSql("DROP INDEX idx_89aa03b25e91d3fb");
        $this->addSql("DROP INDEX idx_89aa03b22b32db58");
        $this->addSql("ALTER TABLE avistamientoimportado DROP edad_id");
        $this->addSql("ALTER TABLE avistamientoimportado DROP sexo_id");
        $this->addSql("ALTER TABLE denuncia DROP latitud");
        $this->addSql("ALTER TABLE denuncia DROP longitud");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("DROP SEQUENCE Coordenada_id_seq CASCADE");
        $this->addSql("DROP SEQUENCE Ejemplar_id_seq CASCADE");
        $this->addSql("DROP TABLE Coordenada");
        $this->addSql("DROP TABLE Ejemplar");
        $this->addSql("ALTER TABLE AvistamientoImportado ADD edad_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE AvistamientoImportado ADD sexo_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE AvistamientoImportado ADD CONSTRAINT fk_89aa03b25e91d3fb FOREIGN KEY (edad_id) REFERENCES edad (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE AvistamientoImportado ADD CONSTRAINT fk_89aa03b22b32db58 FOREIGN KEY (sexo_id) REFERENCES sexo (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE INDEX idx_89aa03b25e91d3fb ON AvistamientoImportado (edad_id)");
        $this->addSql("CREATE INDEX idx_89aa03b22b32db58 ON AvistamientoImportado (sexo_id)");
        $this->addSql("ALTER TABLE Denuncia ADD latitud NUMERIC(9, 2) DEFAULT NULL");
        $this->addSql("ALTER TABLE Denuncia ADD longitud NUMERIC(9, 2) DEFAULT NULL");
    }
}
