<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130725210429 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE TABLE acl_classes (id SERIAL NOT NULL, class_type VARCHAR(200) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_69DD750638A36066 ON acl_classes (class_type)");
        $this->addSql("CREATE TABLE acl_security_identities (id SERIAL NOT NULL, identifier VARCHAR(200) NOT NULL, username BOOLEAN NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_8835EE78772E836AF85E0677 ON acl_security_identities (identifier, username)");
        $this->addSql("CREATE TABLE acl_object_identities (id SERIAL NOT NULL, parent_object_identity_id INT DEFAULT NULL, class_id INT NOT NULL, object_identifier VARCHAR(100) NOT NULL, entries_inheriting BOOLEAN NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_9407E5494B12AD6EA000B10 ON acl_object_identities (object_identifier, class_id)");
        $this->addSql("CREATE INDEX IDX_9407E54977FA751A ON acl_object_identities (parent_object_identity_id)");
        $this->addSql("CREATE TABLE acl_object_identity_ancestors (object_identity_id INT NOT NULL, ancestor_id INT NOT NULL, PRIMARY KEY(object_identity_id, ancestor_id))");
        $this->addSql("CREATE INDEX IDX_825DE2993D9AB4A6 ON acl_object_identity_ancestors (object_identity_id)");
        $this->addSql("CREATE INDEX IDX_825DE299C671CEA1 ON acl_object_identity_ancestors (ancestor_id)");
        $this->addSql("CREATE TABLE acl_entries (id SERIAL NOT NULL, class_id INT NOT NULL, object_identity_id INT DEFAULT NULL, security_identity_id INT NOT NULL, field_name VARCHAR(50) DEFAULT NULL, ace_order SMALLINT NOT NULL, mask INT NOT NULL, granting BOOLEAN NOT NULL, granting_strategy VARCHAR(30) NOT NULL, audit_success BOOLEAN NOT NULL, audit_failure BOOLEAN NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_46C8B806EA000B103D9AB4A64DEF17BCE4289BF4 ON acl_entries (class_id, object_identity_id, field_name, ace_order)");
        $this->addSql("CREATE INDEX IDX_46C8B806EA000B103D9AB4A6DF9183C9 ON acl_entries (class_id, object_identity_id, security_identity_id)");
        $this->addSql("CREATE INDEX IDX_46C8B806EA000B10 ON acl_entries (class_id)");
        $this->addSql("CREATE INDEX IDX_46C8B8063D9AB4A6 ON acl_entries (object_identity_id)");
        $this->addSql("CREATE INDEX IDX_46C8B806DF9183C9 ON acl_entries (security_identity_id)");
        $this->addSql("ALTER TABLE acl_object_identities ADD CONSTRAINT FK_9407E54977FA751A FOREIGN KEY (parent_object_identity_id) REFERENCES acl_object_identities (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE acl_object_identity_ancestors ADD CONSTRAINT FK_825DE2993D9AB4A6 FOREIGN KEY (object_identity_id) REFERENCES acl_object_identities (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE acl_object_identity_ancestors ADD CONSTRAINT FK_825DE299C671CEA1 FOREIGN KEY (ancestor_id) REFERENCES acl_object_identities (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE acl_entries ADD CONSTRAINT FK_46C8B806EA000B10 FOREIGN KEY (class_id) REFERENCES acl_classes (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE acl_entries ADD CONSTRAINT FK_46C8B8063D9AB4A6 FOREIGN KEY (object_identity_id) REFERENCES acl_object_identities (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE acl_entries ADD CONSTRAINT FK_46C8B806DF9183C9 FOREIGN KEY (security_identity_id) REFERENCES acl_security_identities (id) ON UPDATE CASCADE ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE fos_user ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD date_of_birth TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD firstname VARCHAR(64) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD lastname VARCHAR(64) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD website VARCHAR(64) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD biography VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD gender VARCHAR(1) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD locale VARCHAR(8) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD timezone VARCHAR(64) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD phone VARCHAR(64) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD facebook_uid VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD facebook_name VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD facebook_data TEXT DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD twitter_uid VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD twitter_name VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD twitter_data TEXT DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD gplus_uid VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD gplus_name VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD gplus_data TEXT DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD token VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD two_step_code VARCHAR(255) DEFAULT NULL");
        $this->addSql("COMMENT ON COLUMN fos_user.facebook_data IS '(DC2Type:json)'");
        $this->addSql("COMMENT ON COLUMN fos_user.twitter_data IS '(DC2Type:json)'");
        $this->addSql("COMMENT ON COLUMN fos_user.gplus_data IS '(DC2Type:json)'");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE acl_entries DROP CONSTRAINT FK_46C8B806EA000B10");
        $this->addSql("ALTER TABLE acl_entries DROP CONSTRAINT FK_46C8B806DF9183C9");
        $this->addSql("ALTER TABLE acl_object_identities DROP CONSTRAINT FK_9407E54977FA751A");
        $this->addSql("ALTER TABLE acl_object_identity_ancestors DROP CONSTRAINT FK_825DE2993D9AB4A6");
        $this->addSql("ALTER TABLE acl_object_identity_ancestors DROP CONSTRAINT FK_825DE299C671CEA1");
        $this->addSql("ALTER TABLE acl_entries DROP CONSTRAINT FK_46C8B8063D9AB4A6");
        $this->addSql("DROP TABLE acl_classes");
        $this->addSql("DROP TABLE acl_security_identities");
        $this->addSql("DROP TABLE acl_object_identities");
        $this->addSql("DROP TABLE acl_object_identity_ancestors");
        $this->addSql("DROP TABLE acl_entries");
        $this->addSql("ALTER TABLE fos_user DROP created_at");
        $this->addSql("ALTER TABLE fos_user DROP updated_at");
        $this->addSql("ALTER TABLE fos_user DROP date_of_birth");
        $this->addSql("ALTER TABLE fos_user DROP firstname");
        $this->addSql("ALTER TABLE fos_user DROP lastname");
        $this->addSql("ALTER TABLE fos_user DROP website");
        $this->addSql("ALTER TABLE fos_user DROP biography");
        $this->addSql("ALTER TABLE fos_user DROP gender");
        $this->addSql("ALTER TABLE fos_user DROP locale");
        $this->addSql("ALTER TABLE fos_user DROP timezone");
        $this->addSql("ALTER TABLE fos_user DROP phone");
        $this->addSql("ALTER TABLE fos_user DROP facebook_uid");
        $this->addSql("ALTER TABLE fos_user DROP facebook_name");
        $this->addSql("ALTER TABLE fos_user DROP facebook_data");
        $this->addSql("ALTER TABLE fos_user DROP twitter_uid");
        $this->addSql("ALTER TABLE fos_user DROP twitter_name");
        $this->addSql("ALTER TABLE fos_user DROP twitter_data");
        $this->addSql("ALTER TABLE fos_user DROP gplus_uid");
        $this->addSql("ALTER TABLE fos_user DROP gplus_name");
        $this->addSql("ALTER TABLE fos_user DROP gplus_data");
        $this->addSql("ALTER TABLE fos_user DROP token");
        $this->addSql("ALTER TABLE fos_user DROP two_step_code");
    }
}
