<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130627230724 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE SEQUENCE Denuncia_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE TipoDenuncia_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE Denuncia (id INT NOT NULL, municipio_id INT DEFAULT NULL, zona_id INT DEFAULT NULL, tipo_id INT DEFAULT NULL, localidad VARCHAR(255) NOT NULL, latitud NUMERIC(9, 2) DEFAULT NULL, longitud NUMERIC(9, 2) DEFAULT NULL, area NUMERIC(10, 0) NOT NULL, comentario TEXT NOT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_D5505C058BC1BE0 ON Denuncia (municipio_id)");
        $this->addSql("CREATE INDEX IDX_D5505C0104EA8FC ON Denuncia (zona_id)");
        $this->addSql("CREATE INDEX IDX_D5505C0A9276E6C ON Denuncia (tipo_id)");
        $this->addSql("CREATE TABLE TipoDenuncia (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, color VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("ALTER TABLE Denuncia ADD CONSTRAINT FK_D5505C058BC1BE0 FOREIGN KEY (municipio_id) REFERENCES Municipio (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Denuncia ADD CONSTRAINT FK_D5505C0104EA8FC FOREIGN KEY (zona_id) REFERENCES Zona (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Denuncia ADD CONSTRAINT FK_D5505C0A9276E6C FOREIGN KEY (tipo_id) REFERENCES TipoDenuncia (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE Denuncia DROP CONSTRAINT FK_D5505C0A9276E6C");
        $this->addSql("DROP SEQUENCE Denuncia_id_seq CASCADE");
        $this->addSql("DROP SEQUENCE TipoDenuncia_id_seq CASCADE");
        $this->addSql("DROP TABLE Denuncia");
        $this->addSql("DROP TABLE TipoDenuncia");
    }
}
