<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130803184106 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE atributoclave ADD base_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE atributoclave ADD CONSTRAINT FK_D7348F5C6967DF41 FOREIGN KEY (base_id) REFERENCES media__media (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE INDEX IDX_D7348F5C6967DF41 ON atributoclave (base_id)");
        $this->addSql("ALTER TABLE imagen ADD image_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE imagen DROP path");
        $this->addSql("ALTER TABLE imagen ADD CONSTRAINT FK_84B5D7853DA5256D FOREIGN KEY (image_id) REFERENCES media__media (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE INDEX IDX_84B5D7853DA5256D ON imagen (image_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE SEQUENCE acl_entries_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE acl_security_identities_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE acl_classes_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE acl_object_identities_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("ALTER TABLE AtributoClave DROP base_id");
        $this->addSql("ALTER TABLE AtributoClave DROP CONSTRAINT FK_D7348F5C6967DF41");
        $this->addSql("DROP INDEX IDX_D7348F5C6967DF41");
        $this->addSql("ALTER TABLE Imagen ADD path VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE Imagen DROP image_id");
        $this->addSql("ALTER TABLE Imagen DROP CONSTRAINT FK_84B5D7853DA5256D");
        $this->addSql("DROP INDEX IDX_84B5D7853DA5256D");
    }
}
