<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130706111138 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE SEQUENCE ImagenDenuncia_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE ImagenDenuncia (id INT NOT NULL, denuncia_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, path VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_768B272117048D94 ON ImagenDenuncia (denuncia_id)");
        $this->addSql("ALTER TABLE ImagenDenuncia ADD CONSTRAINT FK_768B272117048D94 FOREIGN KEY (denuncia_id) REFERENCES Denuncia (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("DROP SEQUENCE ImagenDenuncia_id_seq CASCADE");
        $this->addSql("DROP TABLE ImagenDenuncia");
    }
}
