imagendenuncia:
    pattern:  /
    defaults: { _controller: "IndiraSimoniBundle:ImagenDenuncia:index" }

imagendenuncia_show:
    pattern:  /{id}/show
    defaults: { _controller: "IndiraSimoniBundle:ImagenDenuncia:show" }

imagendenuncia_new:
    pattern:  /new
    defaults: { _controller: "IndiraSimoniBundle:ImagenDenuncia:new" }

imagendenuncia_create:
    pattern:  /create
    defaults: { _controller: "IndiraSimoniBundle:ImagenDenuncia:create" }
    requirements: { _method: post }

imagendenuncia_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "IndiraSimoniBundle:ImagenDenuncia:edit" }

imagendenuncia_update:
    pattern:  /{id}/update
    defaults: { _controller: "IndiraSimoniBundle:ImagenDenuncia:update" }
    requirements: { _method: post|put }

imagendenuncia_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "IndiraSimoniBundle:ImagenDenuncia:delete" }
    requirements: { _method: post|delete }
